### ISSUE TITLE
Show the user a list of files they have saved.

### ISSUE THREAD

**Issue by Elden123** [Elden123/Hub#1]
When the user presses "Load" a list should appear of all the file files they have saved. e.g HelloWorld.py, myFirst.py, numbers.py. The users should then be able to click on one of the file names and have it load into the editor.

**Comment by Elden123** [comment]
NOTE: "Add real-time database" issue needs to be solved first.

**Comment by ehiggins98** [comment]
This should be "done," but I don't want to close the issue until you have time to check it.
